TwitApp/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TwitApp.views.home', name='home'),
    # url(r'^TwitApp/', include('TwitApp.foo.urls')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('twitai:main'))),
    url(r'^tai/', include('twitai.urls', namespace="twitai")),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Social Auth
    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^twitter/', include('twitfollowing.urls', namespace="twitfollowing"))
)

twitai/urls.py
from django.conf.urls import patterns, include, url
from twitai import views, staff

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login-error$', views.login_error),
    url(r'^staff$', staff.staff_main, name='staff'),
    url(r'^main$', views.main, name='main'),
    url(r'^logout$', views.logout, name='logout')
)

twitfollowing/urls.py
from django.conf.urls import patterns, url

from twitfollowing import views

urlpatterns = patterns('',
    url(r'^recommended$', views.recommended_users_list, name='recommended'),
    url(r'^followed$', views.followed_users_list, name='followed'),
    url(r'^twits/(?P<screen_name>.+)$', views.twits_from_user, name='twits' ),
    url(r'^search/(?P<screen_pattern>.+)$', views.find_screen, name='search' )
)

twitai/models.py
from django.db import models

# Create your models here.

twitfollowing/models.py
from django.db import models

class FollowedUser(models.Model):
    twitter_screen_name = models.CharField(max_length=40, unique=True, blank=False)

twitai/forms.py
from django.forms.fields import CharField
from django.forms.forms import Form


class LoginForm(Form):
    login = CharField()
    password = CharField()

twitai/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from twitai.forms import LoginForm


def index(request):
    return HttpResponse('Hello django')


def login(request):
    if request.user.is_authenticated():
        return redirect('twitai:main')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            return HttpResponse('Great!')

    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


@login_required()
def main(request):
    return render(request, 'main.html')


def login_error(request):
    return render(request, 'login.html', {'message' : 'You did not sign in.', 'form' : LoginForm()})


@login_required()
def logout(request):
    auth_logout(request)
    return redirect('twitai:login')

twitfollowing/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse

from django.shortcuts import render
from TwitApp import settings
from twitfollowing.models import FollowedUser
from twython import Twython
from twython import TwythonAuthError
from social.apps.django_app.default.models import UserSocialAuth
from django.forms.models import modelform_factory

FollowedUserForm = modelform_factory(FollowedUser, fields=('twitter_screen_name',))


def get_twython(request):
    tokens = UserSocialAuth.objects.get(user=request.user, provider='twitter').tokens
    twitter = Twython(settings.SOCIAL_AUTH_TWITTER_KEY,
                      settings.SOCIAL_AUTH_TWITTER_SECRET,
                      tokens['oauth_token'],
                      tokens['oauth_token_secret']
    )
    return twitter


class RecommendedUsersStrategy:
    type = "recommended"

    def __init__(self):
        pass

    def save(self, request, form):
        form.save()

    def all_users(self, request):
        return FollowedUser.objects.all()


class FollowedUsersStrategy:
    type = "followed"

    def __init__(self, twitter_factory):
        self.twitter_factory = twitter_factory

    def save(self, request, form):
        twitter = self.twitter_factory(request)
        twitter.create_friendship(screen_name=form.instance.twitter_screen_name)

    def all_users(self, request):
        twitter = self.twitter_factory(request)
        response = twitter.get_friends_ids(screen_name=request.user.username)
        ids = [str(id) for id in response["ids"]]
        users = twitter.lookup_user(user_id=", ".join(ids))
        names = [{"twitter_screen_name": u["screen_name"]} for u in users]
        return names


def users_list_factory(serving_strategy):
    @login_required()
    def view(request):
        if request.method == 'POST':
            form = FollowedUserForm(request.POST)
            if form.is_valid():
                serving_strategy.save(request, form)
                form = FollowedUserForm()
        else:
            form = FollowedUserForm()
        return render(request, 'twitfollowing/list.html', {'followed_users_list': serving_strategy.all_users(request),
                                                           'form': form, 'type': serving_strategy.type})

    return view


recommended_users_list = users_list_factory(RecommendedUsersStrategy())
followed_users_list = users_list_factory(FollowedUsersStrategy(get_twython))


@login_required()
def twits_from_user(request, screen_name):
    try:
        twitter = get_twython(request)
        twits = twitter.get_user_timeline(screen_name=screen_name)
    except TwythonAuthError:
        return render(request, 'error.html', {'message': 'This is private twitter profile'})

    return render(request, 'twitfollowing/twits.html', {'twits': twits, 'username': screen_name})


@login_required()
def find_screen(request, screen_pattern):
    twitter = get_twython(request)
    users = twitter.search_users(q=screen_pattern, count=10)
    return HttpResponse(json.dumps(users), content_type="application/json")

templates/error.html
{%  extends "main.html" %}

{%  block content %}
    {{ message }}
{%  endblock %}

templates/login.html
{%  extends "main.html" %}


{%  block navbar %}{% endblock %}

{% block sitename %} Login {% endblock %}

{%  block content %}
<a type="button" class="btn btn-primary btn-lg" href="{% url 'social:begin' "twitter" %}">Login using Twitter</a>
{%  endblock %}

templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Twitter App{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "bootstrap/css/bootstrap-theme.min.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "twitai.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "typeahead-bootstrap.css" %}" rel="stylesheet" media="screen">
</head>
<body>
<div class="tai-main">
    <h4><span class="label label-default">{% block sitename %}Twitter App{% endblock %} - Welcome, {{ user.username|default:"New User" }} !</span></h4>
    <div id="navbar">
        {% block navbar %}
         {% include 'navbar.html' %}
        {%  endblock %}
    </div>


    <div id="content">
        <div class="tai-inner">
        {% block content %}
            <h3>This is page for all authenticated users</h3>
        {% endblock %}
        </div>
    </div>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="{% static "bootstrap/js/bootstrap.js" %}"></script>
<script type="text/javascript" src="{% static "bootstrap/js/typeahead.js" %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

templates/navbar.html
<div class="btn-group btn-group-lg">
  <a type="button" class="btn btn-default" href="{%  url 'twitai:main' %}">Main</a>
  <a type="button" class="btn btn-default" href="{% url 'twitfollowing:followed'%}">Followed</a>
  <a type="button" class="btn btn-default" href="{% url 'twitfollowing:recommended'%}">Recommended</a>
  <a type="button" class="btn btn-default" href="{% url 'twitai:logout'%}">Logout</a>
</div>

templates/staff.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    {% include 'navbar.html' with sitename="staff" %}
    <h1>This is staff only page</h1>
</body>
</html>

twitfollowing/templates/twitfollowing/list.html
{% extends "main.html" %}
{% load staticfiles %}

{% block sitename %}
    {{ type }} Users
{% endblock %}

{% block content %}
{% if user.is_active and user.is_staff %}
    <div class="panel panel-default">
        <div class="panel-heading">Add {{ type }} user</div>
        <div class="panel-body">

            {% with fullurl='twitfollowing:'|add:type %}
            <form action="{% url fullurl %}" method="post">{% csrf_token %}
            {% endwith %}
                {{ form.as_p }}
                <input class="btn btn-info" type="submit" value="Add!"/>
            </form>
        </div>
    </div>
{% endif %}
{% if followed_users_list %}
    <ul class="list-group">
    <a class="list-group-item active">
        All  {{ type }} users:
    </a>
    {% for user in followed_users_list %}
        <a class="list-group-item" href="{% url 'twitfollowing:twits' user.twitter_screen_name %}">{{ user.twitter_screen_name }}</a>
    {% endfor %}
    </ul>
{% else %}
    <p>No  {{ type }} users are available.</p>
{% endif %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "myJsTemplateEngine.js" %}"></script>
    <script type="text/javascript">
        $('#{{ form.twitter_screen_name.auto_id }}').typeahead({
            name: 'twitter_screen_name',
            valueKey: 'screen_name',
            remote: {url: '{% url 'twitfollowing:search' 'QUERY' %}',
                wildcard: 'QUERY'},
            limit: 10,
            template: [
                    '<p class="twit-screen-name">##screen_name</p>',
                    '<p class="twit-name">##name</p>',
                    '<p class="twit-description">##description</p>'
                ].join(''),
            engine: MyEngine
        });
    </script>
{% endblock %}

twitfollowing/templates/twitfollowing/twits.html
{% extends "main.html" %}


{% block sitename %}
    Twits of user: {{ username }}
{% endblock %}


{% block content %}

{% if twits %}
    <ul class="list-group">
    {% for t in twits %}
        <li class="list-group-item">{{ t.text }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No twits are available.</p>
{% endif %}

{% endblock %}